[package]
name = "checkr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
log = "0.4.21"
log4rs = "1.3.0"
nix = "0.17.0"
serde = "1.0.198"
